### ISSUE TITLE
Use asyncio

### ISSUE THREAD

**Issue by Eloston** [TheEnigmaBlade/holo#2]
Since you're already requiring Python 3.4 or higher, I suggest using [asyncio](https://docs.python.org/3/library/asyncio.html). It provides a nice generator-based event loop, which makes things cleaner and more flexible as opposed to invoking holo multiple times.

For HTTP connections, there's [aiohttp](https://github.com/KeepSafe/aiohttp). I don't know of any reddit clients that use asyncio.

**Comment by TheEnigmaBlade** [comment]
While I'm sure asyncio has its uses, it seems a bit overkill for this project. I purposefully designed around the nonuse of an event loop so run-time parameters can be changed on the fly, and I'm not sure I want to do a complete design 180. Thanks for the suggestion, though.
